version: "3.7"
services:
  mysql:
    image: "mysql:8.0"
    working_dir: /app
    restart: unless-stopped
    volumes:
      - ".:/app"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "8889:3306"
    networks:
      - nginx-fpm

  webserver:
    image: "nginx:alpine"
    working_dir: /app
    restart: unless-stopped
    volumes:
      - ".:/app"
      - "./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8888:80"
    networks:
      - nginx-fpm

  php-fpm:
    build: docker/php-fpm
    working_dir: /app
    restart: unless-stopped
    volumes:
      - ".:/app"
      - "./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini"
    networks:
      - nginx-fpm

networks:
  nginx-fpm:
