version: "3.7"
services:
  mysql:
    image: "mysql:8.0"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - nginx-fpm

  webserver:
    build: docker/nginx
    restart: unless-stopped
    volumes:
      - ".:/app"
    ports:
      - "8888:80"
      - "443:443"
    networks:
      - nginx-fpm

  php-fpm:
    build: docker/php-fpm
    working_dir: /app
    restart: unless-stopped
    volumes:
      - ".:/app"
      - "./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini"
    networks:
      - nginx-fpm

networks:
  nginx-fpm:
